/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problem5;

/**
 *
 * @author manxboy
 */
public class SurveyForm extends javax.swing.JFrame {

    /**
     * Creates new form SurveyForm
     */
    public SurveyForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        shooterCheckBox = new javax.swing.JCheckBox();
        strategyCheckBox = new javax.swing.JCheckBox();
        arcadeCheckBox = new javax.swing.JCheckBox();
        fighterCheckBox = new javax.swing.JCheckBox();
        rpgCheckBox = new javax.swing.JCheckBox();
        sportsCheckBox = new javax.swing.JCheckBox();
        platformerCheckBox = new javax.swing.JCheckBox();
        puzzleCheckBox = new javax.swing.JCheckBox();
        otherCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        hoursPerWeekComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        currentGamesTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Please answer the following survey.");

        jLabel2.setText("1. What types of games do you like playing (check all that apply)");

        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        shooterCheckBox.setText("Shooters");
        jPanel2.add(shooterCheckBox);

        strategyCheckBox.setText("Strategy");
        jPanel2.add(strategyCheckBox);

        arcadeCheckBox.setText("Arcade");
        jPanel2.add(arcadeCheckBox);

        fighterCheckBox.setText("Fighters");
        jPanel2.add(fighterCheckBox);

        rpgCheckBox.setText("RPG");
        jPanel2.add(rpgCheckBox);

        sportsCheckBox.setText("Sports");
        jPanel2.add(sportsCheckBox);

        platformerCheckBox.setText("Platformers");
        jPanel2.add(platformerCheckBox);

        puzzleCheckBox.setText("Puzzle");
        jPanel2.add(puzzleCheckBox);

        otherCheckBox.setText("Other");
        jPanel2.add(otherCheckBox);

        jLabel3.setText("2. How many hours per week do you spend gaming?");

        hoursPerWeekComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< 5 hours", "< 10 hours", "< 15 hours", "15 + hours" }));

        jLabel4.setText("3. Enter a few games you're playing right now (separated by commas)");

        submitButton.setText("Submit");
        submitButton.setPreferredSize(new java.awt.Dimension(140, 48));
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel3.add(submitButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(currentGamesTextField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 170, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(hoursPerWeekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hoursPerWeekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentGamesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //Shooters, Fighters, Platformers, Strategy, RPG, Puzzle, Arcade, Sports, Other
        Survey survey = new Survey(
                new boolean[] {
                    shooterCheckBox.getModel().isSelected(),
                    fighterCheckBox.getModel().isSelected(),
                    platformerCheckBox.getModel().isSelected(),
                    strategyCheckBox.getModel().isSelected(),
                    rpgCheckBox.getModel().isSelected(),
                    puzzleCheckBox.getModel().isSelected(),
                    arcadeCheckBox.getModel().isSelected(),
                    sportsCheckBox.getModel().isSelected(),
                    otherCheckBox.getModel().isSelected(),
                },
                hoursPerWeekComboBox.getSelectedIndex(),
                currentGamesTextField.getText()
        );
        
        Survey.SaveSurvey(survey);
        
        System.exit(0);
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SurveyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox arcadeCheckBox;
    private javax.swing.JTextField currentGamesTextField;
    private javax.swing.JCheckBox fighterCheckBox;
    private javax.swing.JComboBox<String> hoursPerWeekComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox otherCheckBox;
    private javax.swing.JCheckBox platformerCheckBox;
    private javax.swing.JCheckBox puzzleCheckBox;
    private javax.swing.JCheckBox rpgCheckBox;
    private javax.swing.JCheckBox shooterCheckBox;
    private javax.swing.JCheckBox sportsCheckBox;
    private javax.swing.JCheckBox strategyCheckBox;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
